version: "2"
run:
  concurrency: 4
  timeout: 5m
linters:
  default: fast
  enable:
    - wsl_v5
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unused
    - revive
    - gocritic
    - bodyclose
    - unparam
    - cyclop
    - dupl
    - goconst
    - funlen
    - depguard
    - misspell
    - forbidigo
    - rowserrcheck
    - sqlclosecheck
    - noctx
    - copyloopvar
  disable:
    - wsl
    - wsl_v5
    - depguard
    - mnd
    - lll
    - cyclop
    - gocyclo
    - nestif
    - gocognit
    - nlreturn
    - funcorder
    - funlen
    - testpackage
    - gochecknoinits
    - maintidx
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: info
formatters:
  enable:
    - gofumpt
    - gofmt
    - gci
    - golines
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/jlrosende/project-manager)
      custom-order: true
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
output:
  formats:
    text:
      path: stderr
      colors: true
