// Code generated by MockGen. DO NOT EDIT.
// Source: project_port.go
//
// Generated by this command:
//
//	mockgen -source=project_port.go -destination=../../../mocks/mock_project_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/jlrosende/project-manager/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectService is a mock of ProjectService interface.
type MockProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceMockRecorder
	isgomock struct{}
}

// MockProjectServiceMockRecorder is the mock recorder for MockProjectService.
type MockProjectServiceMockRecorder struct {
	mock *MockProjectService
}

// NewMockProjectService creates a new mock instance.
func NewMockProjectService(ctrl *gomock.Controller) *MockProjectService {
	mock := &MockProjectService{ctrl: ctrl}
	mock.recorder = &MockProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectService) EXPECT() *MockProjectServiceMockRecorder {
	return m.recorder
}

// AddEnvironment mocks base method.
func (m *MockProjectService) AddEnvironment(projectName string, env *domain.Environment, envVars domain.EnvVars) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEnvironment", projectName, env, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEnvironment indicates an expected call of AddEnvironment.
func (mr *MockProjectServiceMockRecorder) AddEnvironment(projectName, env, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEnvironment", reflect.TypeOf((*MockProjectService)(nil).AddEnvironment), projectName, env, envVars)
}

// Create mocks base method.
func (m *MockProjectService) Create(name, path, subproject, shell, envFile string, envVars domain.EnvVars, git *domain.GitConfig) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, path, subproject, shell, envFile, envVars, git)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectServiceMockRecorder) Create(name, path, subproject, shell, envFile, envVars, git any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectService)(nil).Create), name, path, subproject, shell, envFile, envVars, git)
}

// Delete mocks base method.
func (m *MockProjectService) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectServiceMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectService)(nil).Delete), name)
}

// DeleteProject mocks base method.
func (m *MockProjectService) DeleteProject(ctx context.Context, options domain.ProjectDeleteOptions) (*domain.ProjectDeleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, options)
	ret0, _ := ret[0].(*domain.ProjectDeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectServiceMockRecorder) DeleteProject(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectService)(nil).DeleteProject), ctx, options)
}

// List mocks base method.
func (m *MockProjectService) List() ([]*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectService)(nil).List))
}

// Load mocks base method.
func (m *MockProjectService) Load(name string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", name)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockProjectServiceMockRecorder) Load(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockProjectService)(nil).Load), name)
}

// UpdateEnvironment mocks base method.
func (m *MockProjectService) UpdateEnvironment(projectName, originalEnvName string, env *domain.Environment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironment", projectName, originalEnvName, env)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnvironment indicates an expected call of UpdateEnvironment.
func (mr *MockProjectServiceMockRecorder) UpdateEnvironment(projectName, originalEnvName, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironment", reflect.TypeOf((*MockProjectService)(nil).UpdateEnvironment), projectName, originalEnvName, env)
}

// UpdateProject mocks base method.
func (m *MockProjectService) UpdateProject(project *domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", project)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectServiceMockRecorder) UpdateProject(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectService)(nil).UpdateProject), project)
}

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// AddEnvironment mocks base method.
func (m *MockProjectRepository) AddEnvironment(projectName string, env *domain.Environment, envVars domain.EnvVars) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEnvironment", projectName, env, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEnvironment indicates an expected call of AddEnvironment.
func (mr *MockProjectRepositoryMockRecorder) AddEnvironment(projectName, env, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEnvironment", reflect.TypeOf((*MockProjectRepository)(nil).AddEnvironment), projectName, env, envVars)
}

// Create mocks base method.
func (m *MockProjectRepository) Create(name, path, subproject, shell, envFile string, envVars domain.EnvVars, git *domain.GitConfig) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, path, subproject, shell, envFile, envVars, git)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectRepositoryMockRecorder) Create(name, path, subproject, shell, envFile, envVars, git any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRepository)(nil).Create), name, path, subproject, shell, envFile, envVars, git)
}

// Delete mocks base method.
func (m *MockProjectRepository) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRepositoryMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRepository)(nil).Delete), name)
}

// FinalizeDeletion mocks base method.
func (m *MockProjectRepository) FinalizeDeletion(ctx context.Context, identifier domain.ProjectIdentifier, scope domain.DeleteScope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeDeletion", ctx, identifier, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeDeletion indicates an expected call of FinalizeDeletion.
func (mr *MockProjectRepositoryMockRecorder) FinalizeDeletion(ctx, identifier, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeDeletion", reflect.TypeOf((*MockProjectRepository)(nil).FinalizeDeletion), ctx, identifier, scope)
}

// List mocks base method.
func (m *MockProjectRepository) List() ([]*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRepository)(nil).List))
}

// ResolveIdentifier mocks base method.
func (m *MockProjectRepository) ResolveIdentifier(ctx context.Context, lookup domain.ProjectIdentifier) (domain.ProjectIdentifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIdentifier", ctx, lookup)
	ret0, _ := ret[0].(domain.ProjectIdentifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveIdentifier indicates an expected call of ResolveIdentifier.
func (mr *MockProjectRepositoryMockRecorder) ResolveIdentifier(ctx, lookup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIdentifier", reflect.TypeOf((*MockProjectRepository)(nil).ResolveIdentifier), ctx, lookup)
}

// UpdateEnvironment mocks base method.
func (m *MockProjectRepository) UpdateEnvironment(projectName, originalEnvName string, env *domain.Environment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironment", projectName, originalEnvName, env)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnvironment indicates an expected call of UpdateEnvironment.
func (mr *MockProjectRepositoryMockRecorder) UpdateEnvironment(projectName, originalEnvName, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironment", reflect.TypeOf((*MockProjectRepository)(nil).UpdateEnvironment), projectName, originalEnvName, env)
}

// UpdateProject mocks base method.
func (m *MockProjectRepository) UpdateProject(project *domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", project)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectRepositoryMockRecorder) UpdateProject(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectRepository)(nil).UpdateProject), project)
}
