// Code generated by MockGen. DO NOT EDIT.
// Source: shell_port.go
//
// Generated by this command:
//
//	mockgen -source=shell_port.go -destination=../../../mocks/mock_shell_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShellService is a mock of ShellService interface.
type MockShellService struct {
	ctrl     *gomock.Controller
	recorder *MockShellServiceMockRecorder
	isgomock struct{}
}

// MockShellServiceMockRecorder is the mock recorder for MockShellService.
type MockShellServiceMockRecorder struct {
	mock *MockShellService
}

// NewMockShellService creates a new mock instance.
func NewMockShellService(ctrl *gomock.Controller) *MockShellService {
	mock := &MockShellService{ctrl: ctrl}
	mock.recorder = &MockShellServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShellService) EXPECT() *MockShellServiceMockRecorder {
	return m.recorder
}

// Kill mocks base method.
func (m *MockShellService) Kill() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kill")
	ret0, _ := ret[0].(error)
	return ret0
}

// Kill indicates an expected call of Kill.
func (mr *MockShellServiceMockRecorder) Kill() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MockShellService)(nil).Kill))
}

// Start mocks base method.
func (m *MockShellService) Start() (*os.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(*os.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockShellServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockShellService)(nil).Start))
}

// Wait mocks base method.
func (m *MockShellService) Wait() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockShellServiceMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockShellService)(nil).Wait))
}

// MockShellRepository is a mock of ShellRepository interface.
type MockShellRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShellRepositoryMockRecorder
	isgomock struct{}
}

// MockShellRepositoryMockRecorder is the mock recorder for MockShellRepository.
type MockShellRepositoryMockRecorder struct {
	mock *MockShellRepository
}

// NewMockShellRepository creates a new mock instance.
func NewMockShellRepository(ctrl *gomock.Controller) *MockShellRepository {
	mock := &MockShellRepository{ctrl: ctrl}
	mock.recorder = &MockShellRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShellRepository) EXPECT() *MockShellRepositoryMockRecorder {
	return m.recorder
}

// Kill mocks base method.
func (m *MockShellRepository) Kill() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kill")
	ret0, _ := ret[0].(error)
	return ret0
}

// Kill indicates an expected call of Kill.
func (mr *MockShellRepositoryMockRecorder) Kill() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MockShellRepository)(nil).Kill))
}

// Start mocks base method.
func (m *MockShellRepository) Start() (*os.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(*os.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockShellRepositoryMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockShellRepository)(nil).Start))
}

// Wait mocks base method.
func (m *MockShellRepository) Wait() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wait indicates an expected call of Wait.
func (mr *MockShellRepositoryMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockShellRepository)(nil).Wait))
}
