// Code generated by MockGen. DO NOT EDIT.
// Source: env_vars_port.go
//
// Generated by this command:
//
//	mockgen -source=env_vars_port.go -destination=../../../mocks/mock_env_vars_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/jlrosende/project-manager/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvVarsService is a mock of EnvVarsService interface.
type MockEnvVarsService struct {
	ctrl     *gomock.Controller
	recorder *MockEnvVarsServiceMockRecorder
	isgomock struct{}
}

// MockEnvVarsServiceMockRecorder is the mock recorder for MockEnvVarsService.
type MockEnvVarsServiceMockRecorder struct {
	mock *MockEnvVarsService
}

// NewMockEnvVarsService creates a new mock instance.
func NewMockEnvVarsService(ctrl *gomock.Controller) *MockEnvVarsService {
	mock := &MockEnvVarsService{ctrl: ctrl}
	mock.recorder = &MockEnvVarsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvVarsService) EXPECT() *MockEnvVarsServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEnvVarsService) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEnvVarsServiceMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEnvVarsService)(nil).Delete), ctx, path)
}

// Load mocks base method.
func (m *MockEnvVarsService) Load(path string) (domain.EnvVars, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(domain.EnvVars)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockEnvVarsServiceMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockEnvVarsService)(nil).Load), path)
}

// Save mocks base method.
func (m *MockEnvVarsService) Save(path string, envVars map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", path, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEnvVarsServiceMockRecorder) Save(path, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEnvVarsService)(nil).Save), path, envVars)
}

// MockEnvVarsRepository is a mock of EnvVarsRepository interface.
type MockEnvVarsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnvVarsRepositoryMockRecorder
	isgomock struct{}
}

// MockEnvVarsRepositoryMockRecorder is the mock recorder for MockEnvVarsRepository.
type MockEnvVarsRepositoryMockRecorder struct {
	mock *MockEnvVarsRepository
}

// NewMockEnvVarsRepository creates a new mock instance.
func NewMockEnvVarsRepository(ctrl *gomock.Controller) *MockEnvVarsRepository {
	mock := &MockEnvVarsRepository{ctrl: ctrl}
	mock.recorder = &MockEnvVarsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvVarsRepository) EXPECT() *MockEnvVarsRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEnvVarsRepository) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEnvVarsRepositoryMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEnvVarsRepository)(nil).Delete), ctx, path)
}

// Load mocks base method.
func (m *MockEnvVarsRepository) Load(path string) (domain.EnvVars, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(domain.EnvVars)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockEnvVarsRepositoryMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockEnvVarsRepository)(nil).Load), path)
}

// Save mocks base method.
func (m *MockEnvVarsRepository) Save(path string, envVars map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", path, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEnvVarsRepositoryMockRecorder) Save(path, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEnvVarsRepository)(nil).Save), path, envVars)
}
