// Code generated by MockGen. DO NOT EDIT.
// Source: filesystem_port.go
//
// Generated by this command:
//
//	mockgen -source=filesystem_port.go -destination=../../../mocks/mock_filesystem_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	domain "github.com/jlrosende/project-manager/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFilesystem is a mock of Filesystem interface.
type MockFilesystem struct {
	ctrl     *gomock.Controller
	recorder *MockFilesystemMockRecorder
	isgomock struct{}
}

// MockFilesystemMockRecorder is the mock recorder for MockFilesystem.
type MockFilesystemMockRecorder struct {
	mock *MockFilesystem
}

// NewMockFilesystem creates a new mock instance.
func NewMockFilesystem(ctrl *gomock.Controller) *MockFilesystem {
	mock := &MockFilesystem{ctrl: ctrl}
	mock.recorder = &MockFilesystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesystem) EXPECT() *MockFilesystemMockRecorder {
	return m.recorder
}

// Abs mocks base method.
func (m *MockFilesystem) Abs(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abs", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Abs indicates an expected call of Abs.
func (mr *MockFilesystemMockRecorder) Abs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abs", reflect.TypeOf((*MockFilesystem)(nil).Abs), path)
}

// CreateBackup mocks base method.
func (m *MockFilesystem) CreateBackup(ctx context.Context, target domain.ProjectIdentifier, req *domain.BackupRequest) (*domain.BackupArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackup", ctx, target, req)
	ret0, _ := ret[0].(*domain.BackupArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBackup indicates an expected call of CreateBackup.
func (mr *MockFilesystemMockRecorder) CreateBackup(ctx, target, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackup", reflect.TypeOf((*MockFilesystem)(nil).CreateBackup), ctx, target, req)
}

// EnsureDir mocks base method.
func (m *MockFilesystem) EnsureDir(path string, mode fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDir", path, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDir indicates an expected call of EnsureDir.
func (mr *MockFilesystemMockRecorder) EnsureDir(path, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDir", reflect.TypeOf((*MockFilesystem)(nil).EnsureDir), path, mode)
}

// ExecuteDeletion mocks base method.
func (m *MockFilesystem) ExecuteDeletion(ctx context.Context, plan *domain.ProjectDeletePlan) ([]domain.DeletionArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDeletion", ctx, plan)
	ret0, _ := ret[0].([]domain.DeletionArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDeletion indicates an expected call of ExecuteDeletion.
func (mr *MockFilesystemMockRecorder) ExecuteDeletion(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDeletion", reflect.TypeOf((*MockFilesystem)(nil).ExecuteDeletion), ctx, plan)
}

// ExpandHome mocks base method.
func (m *MockFilesystem) ExpandHome(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandHome", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExpandHome indicates an expected call of ExpandHome.
func (mr *MockFilesystemMockRecorder) ExpandHome(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandHome", reflect.TypeOf((*MockFilesystem)(nil).ExpandHome), path)
}

// IsAbs mocks base method.
func (m *MockFilesystem) IsAbs(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAbs", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAbs indicates an expected call of IsAbs.
func (mr *MockFilesystemMockRecorder) IsAbs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAbs", reflect.TypeOf((*MockFilesystem)(nil).IsAbs), path)
}

// IsDirEmpty mocks base method.
func (m *MockFilesystem) IsDirEmpty(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirEmpty", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDirEmpty indicates an expected call of IsDirEmpty.
func (mr *MockFilesystemMockRecorder) IsDirEmpty(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirEmpty", reflect.TypeOf((*MockFilesystem)(nil).IsDirEmpty), path)
}

// Join mocks base method.
func (m *MockFilesystem) Join(elem ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range elem {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockFilesystemMockRecorder) Join(elem ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockFilesystem)(nil).Join), elem...)
}

// PlanBackup mocks base method.
func (m *MockFilesystem) PlanBackup(ctx context.Context, target domain.ProjectIdentifier, req *domain.BackupRequest, dryRun bool) (*domain.BackupArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlanBackup", ctx, target, req, dryRun)
	ret0, _ := ret[0].(*domain.BackupArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlanBackup indicates an expected call of PlanBackup.
func (mr *MockFilesystemMockRecorder) PlanBackup(ctx, target, req, dryRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlanBackup", reflect.TypeOf((*MockFilesystem)(nil).PlanBackup), ctx, target, req, dryRun)
}

// PlanDeletion mocks base method.
func (m *MockFilesystem) PlanDeletion(ctx context.Context, target domain.ProjectIdentifier, scope domain.DeleteScope, backup *domain.BackupRequest) (*domain.ProjectDeletePlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlanDeletion", ctx, target, scope, backup)
	ret0, _ := ret[0].(*domain.ProjectDeletePlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlanDeletion indicates an expected call of PlanDeletion.
func (mr *MockFilesystemMockRecorder) PlanDeletion(ctx, target, scope, backup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlanDeletion", reflect.TypeOf((*MockFilesystem)(nil).PlanDeletion), ctx, target, scope, backup)
}

// Remove mocks base method.
func (m *MockFilesystem) Remove(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFilesystemMockRecorder) Remove(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFilesystem)(nil).Remove), path)
}

// Rename mocks base method.
func (m *MockFilesystem) Rename(oldPath, newPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldPath, newPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockFilesystemMockRecorder) Rename(oldPath, newPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockFilesystem)(nil).Rename), oldPath, newPath)
}

// UserHomeDir mocks base method.
func (m *MockFilesystem) UserHomeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserHomeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserHomeDir indicates an expected call of UserHomeDir.
func (mr *MockFilesystemMockRecorder) UserHomeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserHomeDir", reflect.TypeOf((*MockFilesystem)(nil).UserHomeDir))
}

// WriteFile mocks base method.
func (m *MockFilesystem) WriteFile(path string, data []byte, mode fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, data, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFilesystemMockRecorder) WriteFile(path, data, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFilesystem)(nil).WriteFile), path, data, mode)
}
