// Code generated by MockGen. DO NOT EDIT.
// Source: git_port.go
//
// Generated by this command:
//
//	mockgen -source=git_port.go -destination=../../../mocks/mock_git_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/jlrosende/project-manager/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGitService is a mock of GitService interface.
type MockGitService struct {
	ctrl     *gomock.Controller
	recorder *MockGitServiceMockRecorder
	isgomock struct{}
}

// MockGitServiceMockRecorder is the mock recorder for MockGitService.
type MockGitServiceMockRecorder struct {
	mock *MockGitService
}

// NewMockGitService creates a new mock instance.
func NewMockGitService(ctrl *gomock.Controller) *MockGitService {
	mock := &MockGitService{ctrl: ctrl}
	mock.recorder = &MockGitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitService) EXPECT() *MockGitServiceMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockGitService) Load(path string) (*domain.GitConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(*domain.GitConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockGitServiceMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockGitService)(nil).Load), path)
}

// LoadGlobal mocks base method.
func (m *MockGitService) LoadGlobal() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGlobal")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadGlobal indicates an expected call of LoadGlobal.
func (mr *MockGitServiceMockRecorder) LoadGlobal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGlobal", reflect.TypeOf((*MockGitService)(nil).LoadGlobal))
}

// RemoveHooks mocks base method.
func (m *MockGitService) RemoveHooks(ctx context.Context, project domain.ProjectIdentifier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHooks", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHooks indicates an expected call of RemoveHooks.
func (mr *MockGitServiceMockRecorder) RemoveHooks(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHooks", reflect.TypeOf((*MockGitService)(nil).RemoveHooks), ctx, project)
}

// Save mocks base method.
func (m *MockGitService) Save(path string, gitConfig *domain.GitConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", path, gitConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGitServiceMockRecorder) Save(path, gitConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGitService)(nil).Save), path, gitConfig)
}

// SaveGlobal mocks base method.
func (m *MockGitService) SaveGlobal(home string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGlobal", home)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGlobal indicates an expected call of SaveGlobal.
func (mr *MockGitServiceMockRecorder) SaveGlobal(home any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGlobal", reflect.TypeOf((*MockGitService)(nil).SaveGlobal), home)
}

// UpdateIncludeIf mocks base method.
func (m *MockGitService) UpdateIncludeIf(gitdir, perProjectPath, subproject string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncludeIf", gitdir, perProjectPath, subproject)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncludeIf indicates an expected call of UpdateIncludeIf.
func (mr *MockGitServiceMockRecorder) UpdateIncludeIf(gitdir, perProjectPath, subproject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncludeIf", reflect.TypeOf((*MockGitService)(nil).UpdateIncludeIf), gitdir, perProjectPath, subproject)
}

// MockGitRepository is a mock of GitRepository interface.
type MockGitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryMockRecorder is the mock recorder for MockGitRepository.
type MockGitRepositoryMockRecorder struct {
	mock *MockGitRepository
}

// NewMockGitRepository creates a new mock instance.
func NewMockGitRepository(ctrl *gomock.Controller) *MockGitRepository {
	mock := &MockGitRepository{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepository) EXPECT() *MockGitRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockGitRepository) Load(path string) (*domain.GitConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(*domain.GitConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockGitRepositoryMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockGitRepository)(nil).Load), path)
}

// LoadGlobal mocks base method.
func (m *MockGitRepository) LoadGlobal() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGlobal")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadGlobal indicates an expected call of LoadGlobal.
func (mr *MockGitRepositoryMockRecorder) LoadGlobal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGlobal", reflect.TypeOf((*MockGitRepository)(nil).LoadGlobal))
}

// RemoveHooks mocks base method.
func (m *MockGitRepository) RemoveHooks(ctx context.Context, project domain.ProjectIdentifier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHooks", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHooks indicates an expected call of RemoveHooks.
func (mr *MockGitRepositoryMockRecorder) RemoveHooks(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHooks", reflect.TypeOf((*MockGitRepository)(nil).RemoveHooks), ctx, project)
}

// Save mocks base method.
func (m *MockGitRepository) Save(path string, gitConfig *domain.GitConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", path, gitConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGitRepositoryMockRecorder) Save(path, gitConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGitRepository)(nil).Save), path, gitConfig)
}

// SaveGlobal mocks base method.
func (m *MockGitRepository) SaveGlobal(home string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGlobal", home)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGlobal indicates an expected call of SaveGlobal.
func (mr *MockGitRepositoryMockRecorder) SaveGlobal(home any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGlobal", reflect.TypeOf((*MockGitRepository)(nil).SaveGlobal), home)
}

// UpdateIncludeIf mocks base method.
func (m *MockGitRepository) UpdateIncludeIf(gitdir, perProjectPath, subproject string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncludeIf", gitdir, perProjectPath, subproject)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncludeIf indicates an expected call of UpdateIncludeIf.
func (mr *MockGitRepositoryMockRecorder) UpdateIncludeIf(gitdir, perProjectPath, subproject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncludeIf", reflect.TypeOf((*MockGitRepository)(nil).UpdateIncludeIf), gitdir, perProjectPath, subproject)
}
