services:
  project-manager:
    container_name: project-manager
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file:
      - ./.env

