model_list:
  - model_name: azure/gpt-5
    litellm_params:
      model: azure/gpt-5
      api_base: os.environ/AZURE_OPENAI_ENDPOINT # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_OPENAI_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: os.environ/AZURE_OPENAI_API_VERSION

  - model_name: azure/gpt-4.1
    litellm_params:
      model: azure/gpt-4.1
      api_base: os.environ/AZURE_OPENAI_ENDPOINT # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_OPENAI_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: os.environ/AZURE_OPENAI_API_VERSION

litellm_settings:
  drop_params: True
  cache: True
  cache_params:
    type: local
